### ISSUE TITLE
Support dark theme out of the box

### ISSUE THREAD

**Issue by awazgyawali** [theideasaler/calendar_date_picker2#1]
This package seems promising, it would be great if we added default dark mode color scheme and make the current default theme as light mode.

Also the capability of changing the background color of the dialog should be added.

**Comment by theideasaler** [comment]
Hi @awazgyawali , `dialogBackgroundColor` has been added into `showCalendarDatePicker2Dialog` method.

Regarding the dark mode, currently there is no plan for adding it as all the colors of the Calendar are highly customisable so you probably create the colors you need at the component level.  If you think it is necessary, you could probably create a PR for it, I am happy to review it.
