### ISSUE TITLE
[Feature] Display current month when loading calendar

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [theideasaler/calendar_date_picker2#104]
Hey bro, really nice plugin. Can you please add possibility to display current month when loading calendar?
So the thing is, when I set firstDate to 1 January 2023 and lastDate to 31 December 2023, when calendar loads it first shows me January month, and now is April, I would like initially to display April month.

**Comment by theideasaler** [comment]
Hi @aleksandar-radivojevic when you say `firstDate` and `lastDate`, are you referring to the `config`s or the selections you passed into `value`

**Comment by aleksandar-radivojevic** [comment]
Hey @theideasaler 
I am reffering to CalendarDatePicker2Config firstDate and lastDate

**Comment by aleksandar-radivojevic** [comment]
@theideasaler Well thats the problem, my `value` isn't empty, it has List of DateTimes that have dates in every month, so January, Feb, March.. every month has a few dates in `value`. 
And it is displaying first selected date in value, like you said but I need to display current month even of there is no dates for it and we have dates for earlier months.
Sorry I may describe it bad at first, but I think now that you can understand what I am trying to accomplish.

**Comment by theideasaler** [comment]
I will add it to planned features but there won't be any clear time map for it.

**Comment by theideasaler** [comment]
@aleksandar-radivojevic This feature is introduced in https://github.com/theideasaler/calendar_date_picker2/pull/107,  Please keep an eye on the new release https://pub.dev/packages/calendar_date_picker2

**Comment by aleksandar-radivojevic** [comment]
Thank you so much broooooooooo. 🥳 ❤️ 
Can you also add displayMonthDate in showCalendarDatePicker2Dialog?
