### ISSUE TITLE
[Feature] Dynamically change current month and year based on other events

### ISSUE THREAD

**Issue by HappyMakadiyaS** [theideasaler/calendar_date_picker2#106]
**Use cases**
I have one usecase like select date and update calender UI based on filters like Last Week, Last Month, etc. So Based on filter I want to reflect current month. which is not achievable in the current version.

**Describe the feature you'd like**
Provide extra param feasibility like initialDate. and will update accordingly

**Comment by theideasaler** [comment]
@HappyMakadiyaS  Issue closed as this feature request is a duplication of https://github.com/theideasaler/calendar_date_picker2/issues/104

Any discussion please head to #104
