### ISSUE TITLE
[Bug] Having a pixelate divider between days in Month Grid

### ISSUE THREAD

**Issue by HappyMakadiyaS** [theideasaler/calendar_date_picker2#109]
**Describe the bug**
Divider is visible between rows of the month grid. Need to calculate `tileWidth` accurately enough. 

**Expected behavior**
<img width="349" alt="image" src="https://user-images.githubusercontent.com/97177197/231952438-45200d81-6172-4937-9a13-f5452d3fbcdf.png">

**Actual Behaviour**
<img width="370" alt="image" src="https://user-images.githubusercontent.com/97177197/231952453-f5261d25-684d-4ce4-961c-6d78c9320458.png">

**Comment by theideasaler** [comment]
Please refer to https://github.com/theideasaler/calendar_date_picker2/pull/220 as a workaround fix.
