### ISSUE TITLE
[Feature] Provide Vertical List view of month

### ISSUE THREAD

**Issue by HappyMakadiyaS** [theideasaler/calendar_date_picker2#110]
**Describe the feature you'd like**
Can we have the feasibility of displaying months in the vertical list view?
There are a couple of other packages which give this kind of view. But this package is pretty much fulfilling another requirement also. So, personally prefer to use this package on my end. So It would be very helpful to have list view support.

**Comment by theideasaler** [comment]
Hi @HappyMakadiyaS This requires quite solid efforts, so currently there is no plan to add it. 

I will add a feature flag so if anyone from the community can work on it.

**Comment by theideasaler** [comment]
feature added in https://github.com/theideasaler/calendar_date_picker2/pull/167
