### ISSUE TITLE
[Feature] Get selected values when okButton is customized on dialog

### ISSUE THREAD

**Issue by Ronan-V** [theideasaler/calendar_date_picker2#115]
First of all, I'd like to thank you for the work you are doing with this package. It helps a lot.

**Is your feature request related to a problem? Please describe.**
I'd like to customize okButton on the dialog with showCalendarDatePicker2Dialog. 
This can be done with the okButton argument which overrides the okButton widget but it doesn't seem to be possible to get the selected values and return it like the default okButton does.

**Describe the feature you'd like**
I'd like to customize the okButton of the dialog withtout necessarily change its behavior. 

**Use cases**
Customize the button's decoration.
Change label's language.

Thank you !

**Comment by theideasaler** [comment]
Hi @Ronan-V, 

Custom buttons only affect the UI and should not affect the UX behaviour of getting the returned selected dates. If so then it is a bug and needs a minimal reproducible example for investigation.

**Comment by dev-ravan** [comment]
Hi @Ronan-V  & @theideasaler,
I have the same issue in my case I need to trigger the api on click ok button but its not return the selected date.
