### ISSUE TITLE
Today button

### ISSUE THREAD

**Issue by likhainnotech** [theideasaler/calendar_date_picker2#118]
**Describe the feature you'd like**
Can you add an optional _Today_ button? This is to quickly select today's date.

**Use cases**
User wants to quickly select today's date after he drifted to the past (or the future).

**Comment by theideasaler** [comment]
This won't be implemented, please refer to this closed issue https://github.com/theideasaler/calendar_date_picker2/issues/66

If you need this feature, you can easily achieve it by wrapping `CalendarDatePicker2` into your own wrapper class.
