### ISSUE TITLE
showCalendarDatePicker2Dialog without ActionButtons

### ISSUE THREAD

**Issue by tomasbaran** [theideasaler/calendar_date_picker2#119]
**Is your feature request related to a problem? Please describe.**
nope

**Describe the feature you'd like**
I would like to use showCalendarDatePicker2Dialog without ActionButtons, so would appreciate using `CalendarDatePicker2Config` instead of `CalendarDatePicker2WithActionButtonsConfig` as well as `onValueChanged`

**Use cases**
Add use cases for the feature you're requested

**Comment by theideasaler** [comment]
@tomasbaran You can easily achieve this by wrapping the `CalendarDatePicker2` inside your own dialog function.

No need to make it a separate feature for this.
