### ISSUE TITLE
[Feature] Selecting date range in any direction

### ISSUE THREAD

**Issue by Albert221** [theideasaler/calendar_date_picker2#131]
**Is your feature request related to a problem? Please describe.**
This is something that my UX designer asked for.

**Describe the feature you'd like**
Right now, the _range_ date picker allows only selecting the date range by selecting a date, and then a date following that one (or the same). I'd like to have the ability for the users to select any two dates, even date A, and then date B that's **before** date A.

Those dates could still be normalized in `onValueChanged`, so that they appear in a correct (chronological) order.

---

I'd be willing to make a Pull Request for that, so if you're okay with that just give me a heads-up :)

I could either modify the existing behavior of the `range` calendar type, or introduce a `rangeBidirectional` value for `CalendarDatePicker2Type` with a correct behavior and docs. Or maybe something else that you'd propose?

Cheers!

**Comment by theideasaler** [comment]
Hi @Albert221, 

Thanks for proposing this. I am happy to review this feature. 

I would prefer the 2nd solution by adding a `rangeBidirectional` flag into the config so it will keep the default UX same.
