### ISSUE TITLE
How to prevent selection before and after blocked days

### ISSUE THREAD

**Issue by mohadel92** [theideasaler/calendar_date_picker2#135]
I am using the  `selectableDayPredicate` to prevent selection of blocked days in my app as a range 
but user can select before and after the blocked days e,g
if the blocked days is between [20/9 and 24/9]
now user can select for [18/9 to 25/9]
i would like to prevent this scenario 

1. add `calendar_date_picker2`
2. implement `selectableDayPredicate`
3. select before and after the blocked days
4. the blocked days can be easily selected inside the range

**Expected behavior**
i was expecting not to be able to select these days

**Actual Behaviour**
the days can be selected 

**Screenshots**
<a href="https://ibb.co/89qfBDr"><img src="https://i.ibb.co/jDmQ5vy/f7208a71-4aad-478e-843e-1f0cac3a1430.jpg" alt="f7208a71-4aad-478e-843e-1f0cac3a1430" border="0"></a>

**Comment by kasyanyukd1995** [comment]
I have the same problem

**Comment by mohadel92** [comment]
@kasyanyukd1995 
I have managed to find a work around by 
1- creating an array of blocked days via looping on the biggest day and the smaller day then creating an array of blocked days
Say:
The end day is 20 sep
And the initial day is 15
I will create an array of days by looping on these days and substraction of single day in each loop
[15/9,16/9,17/9,18/9,19/9,20/9]
Then I will pass this array to the picker

> I have the same problem

**Comment by Chuckame** [comment]
Same issue here. I'm currently thinking about a workaround. The solution of @mohadel92 is not really solving at 100%. To fix it, it's not about disabling those days, but more about preventing the range to include disabled days, while those days should still be selectable in fact. 

Idea 1:
"crop" the range end date to the day before the next unavailable day if any, and advertise the user of this cropping by showing an alert like a snack-bar. 

To do that, when onValueChanged is fired with the end date (index 1 of the list), then check if the range contains an unavailable day. If yes, set the range end date to the next closest unavailable minus 1 day, and display the snackbar.

Also, all the days after the next non-selectable day should show that they are not selectable as an end date (but still selectable as a start date, so they have to not be disabled) by setting up the text color to red by example. 

Idea 2:
Nearly the same as idea 1, but by totally unselecting the timerange completely into instead of cropping to force the user to select again a valid range.


I'll provide some code as an example in the next days, and why not a PR as it seems really an important feature when playing with ranges.

**Comment by Chuckame** [comment]
Here is my code: a date time range picker that "crops" the range to the nearest blocked day if any.

```dart
class _DateRangePicker extends StatefulWidget {
  final List<DateTimeRange> unavailableRanges;

  const _DateRangePicker({required this.unavailableRanges});

  @override
  State<_DateRangePicker> createState() => _DateRangePickerState();
}

class _DateRangePickerState extends State<_DateRangePicker> {
  DateTime? _start;
  DateTime? _end;

  @override
  Widget build(BuildContext context) {
    return CalendarDatePicker2(
      config: CalendarDatePicker2Config(
        // todo update le prix total en fonction de la selection
        // todo peut être avoir une modal ?
        firstDate: DateTime.now(),
        rangeBidirectional: false,
        firstDayOfWeek: 1,
        // monday
        lastDate: DateTime.now().add(const Duration(days: 60)),
        calendarType: CalendarDatePicker2Type.range,
        selectableDayPredicate: (day) {
          return widget.unavailableRanges.none((unavailableRange) => unavailableRange.contains(day));
        },
        weekdayLabels: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
      ),
      onValueChanged: (dates) {
        _start = dates.isNotEmpty ? dates[0] : null;
        _end = dates.length > 1 ? dates[1] : null;
        if (_end != null) {
          final nextUnavailableDay = _findNextUnavailableDay(_start!);
          if (nextUnavailableDay != null && DateTimeRange(start: _start!, end: _end!).contains(nextUnavailableDay)) {
            setState(() {
              _end = nextUnavailableDay.subtract(const Duration(days: 1));
            });
          }
        }
      },
      value: [_start, _end],
    );
  }

  DateTime? _findNextUnavailableDay(DateTime startDay) {
    return widget.unavailableRanges.fold<DateTime?>(null, (firstUnavailableDate, range) {
      if (range.start > startDay) {
        if (firstUnavailableDate == null || range.start < firstUnavailableDate) {
          return range.start;
        }
      }
      return firstUnavailableDate;
    });
  }
}
```

There is some useful extensions used there that I've made:
```dart

extension DateTimeRangeExtensions on DateTimeRange {
  bool contains(DateTime date) {
    return date >= start && date <= end;
  }
}

extension DateTimeExtensions on DateTime {
  bool operator >=(DateTime other) {
    return this == other || isAfter(other);
  }

  bool operator >(DateTime other) {
    return isAfter(other);
  }

  bool operator <=(DateTime other) {
    return this == other || isBefore(other);
  }

  bool operator <(DateTime other) {
    return isBefore(other);
  }
}
extension IterableExtensions<T> on Iterable<T> {
  bool any(bool Function(T e) predicate) {
    for (final element in this) {
      if (predicate(element)) {
        return true;
      }
    }
    return false;
  }

  bool none(bool Function(T e) predicate) {
    return !this.any(predicate);
  }

  bool all(bool Function(T e) predicate) {
    for (final element in this) {
      if (!predicate(element)) {
        return false;
      }
    }
    return true;
  }
}
```

And here is the behavior in video.

https://github.com/theideasaler/calendar_date_picker2/assets/16419143/bb7ba9d4-3a2c-40fb-9df3-86ebb9acf1b0

Enjoy ! 🚀

**Comment by murlika0** [comment]
@Chuckame  it's work. Thank's.

**Comment by Chuckame** [comment]
Copy paste should work https://github.com/theideasaler/calendar_date_picker2/issues/135#issuecomment-1825962073

**Comment by Chuckame** [comment]
@3webbg apparently flutter flow already defines datetime operators. The error is explicit : there is already date time operators extensions. Try removing my date time extensions, it should work

**Comment by rightpath1go** [comment]
> already



> ```dart
> _start
> ```

Can you set up one using Flutterflow?

**Comment by theideasaler** [comment]
The most simple way to handle your scenario is to utilize selectableDayPredicate along with your selectedDates list, for example, if you want to exclude Wednesday from your selectable range.  Only the below code will be needed:
```
selectableDayPredicate: (day) {
        if (_rangeDatePickerValueWithDefaultValue.isEmpty ||
            _rangeDatePickerValueWithDefaultValue.length == 2) {
          // exclude Wednesday
          return day.weekday != DateTime.wednesday;
        } else {
          // Make sure range does not contain any Wednesday
          final firstDate = _rangeDatePickerValueWithDefaultValue.first;
          final range = [firstDate!, day]..sort();
          for (var date = range.first;
              date.compareTo(range.last) <= 0;
              date = date.add(const Duration(days: 1))) {
            if (date.weekday == DateTime.wednesday) {
              return false;
            }
          }
        }
        return true;
      },
```
