### ISSUE TITLE
It takes the range date but the time not included with the date

### ISSUE THREAD

**Issue by mahmoudashry98** [theideasaler/calendar_date_picker2#137]
range date:  [2023-10-19 00:00:00.000, 2023-10-20 00:00:00.000]

**Comment by vinodh013** [comment]
HI, @mahmoudashry98, I am getting the same issue.
So, how to solve this issue and get date and time

**Comment by mahmoudashry98** [comment]
you can send me the link i don't remember this issue, but i'm using now
it's have date(day,hour,mins,)
