### ISSUE TITLE
 [Feature] enable the option to display the initial page either on the first date or the last date

### ISSUE THREAD

**Issue by KeroJohn97** [theideasaler/calendar_date_picker2#139]
When the calendar type is set to CalendarDatePicker2Type.range, please enable the option to display the initial page on either the first or last date. 

Currently, when selecting the first date (e.g., 21 August 2023) and the last date (e.g., 21 October 2023), it always displays on the first date. 

I would appreciate your consideration in enhancing this feature to allow the initial page to be displayed on the last date. Thank you for your attention to this matter. Peace.

**Comment by KeroJohn97** [comment]
If feasible, I am willing to contribute by creating a pull request to implement the changes and make it available as an option in the package.

**Comment by theideasaler** [comment]
Hi @KeroJohn97 , have you tried `displayedMonthDate` to control your initial displayed month.

**Comment by KeroJohn97** [comment]
I see! Could we set it up as a variable in the config, so that I have the flexibility to adjust its value as needed?

**Comment by KeroJohn97** [comment]
> Hi @KeroJohn97 , have you tried `displayedMonthDate` to control your initial displayed month.

I see! Could we set it up as a variable in the config, so that I have the flexibility to adjust its value as needed?

**Comment by theideasaler** [comment]
> > Hi @KeroJohn97 , have you tried `displayedMonthDate` to control your initial displayed month.
> 
> I see! Could we set it up as a variable in the config, so that I have the flexibility to adjust its value as needed?

Hi Kero, config is used for static UI control only, for dynamic value like date and displayed month. They will be kept outside `config`
