### ISSUE TITLE
[Feature] Add option to show previous/next month days

### ISSUE THREAD

**Issue by soyllamas** [theideasaler/calendar_date_picker2#143]
### Is your feature request related to a problem? Please describe.
 I'm facing challenges implementing our design using your library. Specifically, we have a Figma that displays previous and next month days to have a consistent padding all around the calendar widget. The design team added those days to avoid showing extra padding in cases where the month only takes up 5 weeks. Since the widget always shows 6 weeks, there are times when the padding looks _off_. Here is an example:

#### Figma Prototype
<img width="350" alt="SCR-20240117-mtdn" src="https://github.com/theideasaler/calendar_date_picker2/assets/15759364/637f69ea-380b-4c0a-bf74-eef8e524b0ae">

#### Currently in production (5 week month)
<img width="350" alt="SCR-20240117-msxo" src="https://github.com/theideasaler/calendar_date_picker2/assets/15759364/0bd6a741-a3b6-4c84-ae35-0bac2a3e17db">

#### Currently in production (6 week month)
<img width="350" alt="SCR-20240117-nuqa" src="https://github.com/theideasaler/calendar_date_picker2/assets/15759364/5dc8ac85-4b31-4b25-a003-fc807dc6249a">

### Describe the feature you'd like
It would be helpful to have a property in the configuration to show days from previous/next months.
```
CalendarDatePicker2(
  config: CalendarDatePicker2Config(
    calendarDisplayOption: CalendarDisplayOption.allDays, // default: CalendarDisplayOption.onlyCurrentMonth
  ),
)
```

### Use cases
- When you need to guarantee the padding around the calendar widget to achieve the desired design.
- When you want the user to have more context into previous/next dates relative to the current month.

**Comment by theideasaler** [comment]
duplicated https://github.com/theideasaler/calendar_date_picker2/issues/161
