### ISSUE TITLE
[Feature]Show previous and last month

### ISSUE THREAD

**Issue by FabianHagedorn** [theideasaler/calendar_date_picker2#152]
In my Application you often have to choose day(s) from last or next month.

It would be nice if it could show the last and next month in addition to the current month. It would look like this:
      left       -       middle       -     right
last month - current month - next month

**Comment by theideasaler** [comment]
Hi @FabianHagedorn, this is not supported and there is no plan for it right now. One suggested workaround is to replace the config.lastMonthIcon and config.nextMonthIcon since they are Widgets.
```
CalendarDataPicker2Config(
lastMonthIcon: Text('${DateTime(displayedMonth.year, displayedMonth.month - 1).toString()}'),
nextMonthIcon: Text('${DateTime(displayedMonth.year, displayedMonth.month + 1).toString()}'),
)
```
