### ISSUE TITLE
Reset Selected Date Range if one of the selected date is unavailable

### ISSUE THREAD

**Issue by rightpath1go** [theideasaler/calendar_date_picker2#153]
I'm using range mode and want to reset the selected range date but I don't know how to do it, a missing piece of feature maybe.

Let's say you have selected March 26 till March 30 but March 28 isn't available so it must reset the selection to March 30 as starting date. I'm building this for a car rental app.

![image](https://github.com/theideasaler/calendar_date_picker2/assets/86422745/bf604b8f-b98f-42bb-9559-fa5f7c5be89a)

Hoping you can assist me on this or add this feature.

**Comment by theideasaler** [comment]
Hi @rightpath1go, could you please refer to https://github.com/theideasaler/calendar_date_picker2/issues/135

**Comment by rightpath1go** [comment]
Thank you for the reference.

**Comment by theideasaler** [comment]
please refer to https://github.com/theideasaler/calendar_date_picker2/issues/135
