### ISSUE TITLE
[Feature] Dynamic calendar height

### ISSUE THREAD

**Issue by jiaqiu-09** [theideasaler/calendar_date_picker2#160]
**Is your feature request related to a problem? Please describe.**
Doesn't seem like a problem.

**Describe the feature you'd like**
Make the height of the red box part disappear.
<img width="252" alt="image" src="https://github.com/theideasaler/calendar_date_picker2/assets/15116421/b2cbc8f3-6008-4363-a55c-a1543e97e077">

**Use cases**
I need use calendar view with dynamic height. Any advice is welcome and appreciated!

**Comment by theideasaler** [comment]
Hi @jiaqiu-09 , this feature has been introduced with the latest release. 

Simply set `dynamicCalendarRows` to `true`
