### ISSUE TITLE
How make white background?

### ISSUE THREAD

**Issue by DartFlutterWorld** [theideasaler/calendar_date_picker2#172]
The lib doesn't support white color. 

dialogBackgroundColor: Colors.white,

**Comment by joaovvrodrigues** [comment]
Just add dialogBackgroundColor inside showCalendarDatePicker2Dialog.

`showCalendarDatePicker2Dialog(
                                                context: context,
                                                dialogBackgroundColor: Theme.of(context).scaffoldBackgroundColor,
                                                config: CalendarDatePicker2WithActionButtonsConfig(`

**Comment by joaovvrodrigues** [comment]
Just add dialogBackgroundColor inside showCalendarDatePicker2Dialog.

` _dates = await showCalendarDatePicker2Dialog(
                                                context: context,
                                                dialogBackgroundColor: Colors.white,
                                                config: CalendarDatePicker2WithActionButtonsConfig(
                                                  allowSameValueSelection: true,
                                                  rangeBidirectional: true,
                                                  centerAlignModePicker: true,
                                                  dayTextStyle: const TextStyle(fontSize: 14),
                                                  monthTextStyle: const TextStyle(fontSize: 14),
                                                  yearTextStyle: const TextStyle(fontSize: 14),
                                                  todayTextStyle: TextStyle(fontSize: 14, color: Theme.of(context).primaryColorLight),
                                                  controlsTextStyle: const TextStyle(fontSize: 14),
                                                  calendarType: CalendarDatePicker2Type.range,
                                                  calendarViewMode: CalendarDatePicker2Mode.day,
                                                  okButton: Container(
                                                      height: 30,
                                                      width: 100,
                                                      decoration: BoxDecoration(
                                                        borderRadius: const BorderRadius.all(Radius.circular(12)),
                                                        color: Theme.of(context).primaryColorDark,
                                                      ),
                                                      child: const Center(
                                                          child: Text(
                                                        'BUSCAR',
                                                        style: TextStyle(color: Colors.white),
                                                      ))),
                                                  cancelButton: const Text('CANCELAR'),
                                                ),
                                                dialogSize: const Size(325, 400),
                                                value: _dates,
                                                borderRadius: const BorderRadius.all(Radius.circular(12))) ??
                                            [];`
                                            
![Captura de Tela 2024-05-23 às 16 42 47](https://github.com/theideasaler/calendar_date_picker2/assets/31359621/d0b130e9-7e69-480c-be86-8c4e6b379231)

**Comment by DartFlutterWorld** [comment]
> showCalendarDatePicker2Dialog

please check on WEB. WEB doesn't support white color!
