### ISSUE TITLE
Allow removing dividers from _MonthPicker and YearPicker

### ISSUE THREAD

**Issue by can-arikan** [theideasaler/calendar_date_picker2#174]
I would like to ask if it is possible you to setup a way to remove Dividers from _MonthPicker and YearPicker Widgets.

**Comment by theideasaler** [comment]
@can-arikan You can hide the dividers in the new release https://github.com/theideasaler/calendar_date_picker2/pull/178

**Comment by can-arikan** [comment]
Thanks a lot
