### ISSUE TITLE
min Size ?

### ISSUE THREAD

**Issue by CharlotteJu** [theideasaler/calendar_date_picker2#176]
Hi, 
I'm using your very good library for a mobile application. Except that on some (recent) phones, I have an overflowed RenderFlex (in width).

I tried to put a CalendarDatePicker2 in my own Dialog and also through the showCalendarDatePicker2Dialog method. I have the same result.

I couldn't find any setting or information about this. So I wanted to know if there was a minimum width required, and if there was a way to minimize the size of the columns to fit?

**Comment by theideasaler** [comment]
There is no min size required by this package. The size consists of day width and paddings which are fixed.
In the new release, you can now change the day width in the new release https://github.com/theideasaler/calendar_date_picker2/pull/178.

By setting [maxDayWidth] you can adjust the calendar to fit your needs but will need some fine-tuning of different sizes props
