### ISSUE TITLE
[Feature] Automatically scroll to the correct page when value is changed externally 

### ISSUE THREAD

**Issue by naamapps** [theideasaler/calendar_date_picker2#185]
**Is your feature request related to a problem? Please describe.**
Currently I'm implementing a two-way binded scroll feature where the user can scroll a list of calendar events and it will select the correct date on the calendar widget.
However I encountered an issue when changing the value, the new date can be in a different month or even year than before, and so the calendar doesn't scroll to the newly selected month, and the user is viewing irrelevant month. 

**Describe the feature you'd like**
When changing the date value externally I would expect the calendar widget would automatically scroll to the relevant month and year. 

**Use cases**
Two way binded scrolling as describe above.

**Comment by theideasaler** [comment]
Hi @HappyMakadiyaS, are you on `CalendarDatePicker2Mode.scroll` mode? Now you can achieve this by providing your own `scrollViewController`

**Comment by naamapps** [comment]
Hi @theideasaler,
Not working with scroll mode. Working with the regular single date picker.
If you can also add a PageController property it would be good too.
Best implementation would be to include the controller property and also a boolean that decides whether to auto animate to the current value page.

**Comment by theideasaler** [comment]
This should be achievable now with the latest release.
More details can be found at https://github.com/theideasaler/calendar_date_picker2/tree/main/example

**Comment by naamapps** [comment]
Thank you so much @theideasaler, but it doesn't seem to work at all..
I've set animateToDisplayedMonthDate to true, tried changing the value externally, still won't auto scroll to the correct month page.

**Comment by naamapps** [comment]
Works like magic, thanks king!
