### ISSUE TITLE
[Feature] Allow passing a scroll controller for scroll view mode

### ISSUE THREAD

**Issue by Chuckame** [theideasaler/calendar_date_picker2#186]
**Describe the feature you'd like**
I would like to have the scroll view into a bottom sheet modal. I also want to close the modal by sliding down the bottom sheet, but this library is managing by itself the constraints and the scrolling, so I'm unable to do this.

I propose to allow passing a `ScrollController` to allow binding it to the `DraggableScrollableSheet`'s scrollController. That way, when scrolling down, the `DraggableScrollableSheet` receives the scroll instead of having a sub-scroll managed, and the modal closes by itself.

This may remove the scroll listener and box constraints parameters, as the user may want to constraint the calendar widget by himself.

**Comment by theideasaler** [comment]
Hi @Chuckame this seems to be a valid feature request. feel free to raise a PR.

**Comment by theideasaler** [comment]
I will work on a version to expose the scrollController from config
