### ISSUE TITLE
[Feature] Can't custom color header weekday label

### ISSUE THREAD

**Issue by longtn-imt** [theideasaler/calendar_date_picker2#196]
I can't custom header weekday

**Describe the feature you'd like**
Config `weekdayLabels` and `weekdayLabelTextStyle` not find position.

**Use cases**
I want to change red color only Sunday. 

**Solution**
Field `weekdayLabels` style `List<Widget>`
Create new field `weekdayBuilder`

**Comment by longtn-imt** [comment]
And can't change **TextStyle** label choose `Month` and `Year`

**Comment by theideasaler** [comment]
Hi @longtn-imt, your feature request sounds related to a bug. Could you please provide a minimum reproducible example for it?

**Comment by longtn-imt** [comment]
I want to change red color of character "S" (Sunday)
and red color "2024" (Year)

<img width="554" alt="Screen Shot 2024-06-24 at 13 32 48" src="https://github.com/theideasaler/calendar_date_picker2/assets/116779782/03695db0-ac7d-4a86-bf7c-f0efa748a2bd">

<details>
  <summary>Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:calendar_date_picker2/calendar_date_picker2.dart';

void main() {
  runApp(const MaterialApp(home: HomePage()));
}

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Calendar DatePicker')),
      body: CalendarDatePicker2(
        config: CalendarDatePicker2Config(
          calendarType: CalendarDatePicker2Type.range,
          dayBuilder: DayBuilder.new,
        ),
        value: const [],
      ),
    );
  }
}

class DayBuilder extends StatelessWidget {
  const DayBuilder({
    super.key,
    required this.date,
    this.textStyle,
    this.decoration,
    this.isSelected,
    this.isDisabled,
    this.isToday,
  });

  final DateTime date;
  final TextStyle? textStyle;
  final BoxDecoration? decoration;
  final bool? isSelected;
  final bool? isDisabled;
  final bool? isToday;

  @override
  Widget build(BuildContext context) {
    final int day = date.day;
    final int weekday = date.weekday;
    final bool isDayOff = weekday == 7;

    return Container(
      alignment: Alignment.center,
      decoration: decoration,
      child: Text(
        MaterialLocalizations.of(context).formatDecimal(day),
        style: textStyle?.copyWith(
          color: isDayOff ? Colors.red : null,
        ),
      ),
    );
  }
}
```
</details>

**Comment by theideasaler** [comment]
@longtn-imt Your requested feature has been added to the latest release. 
https://pub.dev/packages/calendar_date_picker2
You can checkout example for reference.
https://github.com/theideasaler/calendar_date_picker2/blob/main/example/lib/main.dart
