### ISSUE TITLE
[Bug] animateToDisplayedMonthDate:false doesn't disable animation.

### ISSUE THREAD

**Issue by danilolutti** [theideasaler/calendar_date_picker2#211]
`    final config = CalendarDatePicker2WithActionButtonsConfig(
      calendarType: CalendarDatePicker2Type.single,
      selectedDayHighlightColor:kColorBrandBlue, 
      currentDate: DateTime.now(),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 90)),
      animateToDisplayedMonthDate: false
      )`
      
      if I remove firstDate property, animation disappear.
      
![animation](https://github.com/user-attachments/assets/561ed4ff-1d55-451c-9fd9-1f3cc88480a9)

**Comment by theideasaler** [comment]
Hi @danilolutti , could you please provide a minimum reproducible example? I tried to add the same config you provided with the example app but cannot reproduce it.

**Comment by danilolutti** [comment]
Sorry, flutter clean solved the problem.
