### ISSUE TITLE
border radius

### ISSUE THREAD

**Issue by zeref278** [theideasaler/calendar_date_picker2#22]
Can you add a border radius for day indicator, thanks.
![Screen Shot 2022-09-19 at 15 50 01](https://user-images.githubusercontent.com/48389329/190981860-b2e95230-ef85-44d0-bf3c-8021ad0fe32a.png)

**Comment by theideasaler** [comment]
Hi @zeref278, thanks for the suggestion. If you already got an idea of how to implement it, please feel free to submit a PR, and I am happy to review it.

**Comment by zeref278** [comment]
Hi @theideasaler, i'm already create the PR for this suggestion, waiting for your review, thanks.

**Comment by theideasaler** [comment]
Thanks for the quick action, please find my feedback in https://github.com/theideasaler/calendar_date_picker2/pull/23#pullrequestreview-1112028318

**Comment by zeref278** [comment]
I'm already fix it in the new commit.
