### ISSUE TITLE
[Feature] Hide lastMonthIcon and nextMonthIcon

### ISSUE THREAD

**Issue by tomassasovsky** [theideasaler/calendar_date_picker2#224]
**Is your feature request related to a problem? Please describe.**
I need to hide the arrows from `lastMonthIcon` and `nextMonthIcon`. Setting the widgets to an empty container or SizedBox doesn't work since the hit target is already there.

**Describe the feature you'd like**
Add a parameter which hides these buttons.

**Use cases**
Make the package fit a different design.

**Comment by tomassasovsky** [comment]
Doesn't solve my issue, I need to be able to scroll as well - also, that's not very intuitive.

**Comment by anh-lht** [comment]
Could we build custom widgets specifically for these icons? I'm struggling to implement the feature where the month picker shows double arrows for last/next month, allowing year selection when clicked.

**Comment by theideasaler** [comment]
completed in https://github.com/theideasaler/calendar_date_picker2/pull/237
