### ISSUE TITLE
[Bug] When Ok button is tapped, 'onCancelTapped' is called

### ISSUE THREAD

**Issue by tnidigitaldev1** [theideasaler/calendar_date_picker2#27]
Using 'CalendarDatePicker2WithActionButtons' widget when you tap OK button 'widget.onCancelTapped?.call();' is called.

**Screenshots**
![image](https://user-images.githubusercontent.com/98105468/192749845-5e625dbd-e119-4000-b99c-a9826887fb3d.png)

**Comment by theideasaler** [comment]
Hi @tnidigitaldev1, this seems to be a bug. You can create a PR for this fix, or leave it to me and I will get on it later.

**Comment by theideasaler** [comment]
Issued closed with fix https://github.com/theideasaler/calendar_date_picker2/pull/28
