### ISSUE TITLE
[Feature] Physics argument

### ISSUE THREAD

**Issue by MendleM** [theideasaler/calendar_date_picker2#29]
Would love to be able to configure the physics of the horizontal scroll between months.

**Comment by theideasaler** [comment]
Hi @MendleM , are you referring to something which can enable/disable the horizontal scroll?

**Comment by MendleM** [comment]
Not that, no. I mean, when you scroll horizontally between months and you hit the end of the range of allowed months, the default is to show you the blue elastic banding effect which is a product of the default physics behavior.

If I could set `physics: const BouncingScrollPhysics()` for example, the motion would look a lot more elastic and smooth for my particular use-case.

Hope that makes sense.

**Comment by theideasaler** [comment]
resolved in https://github.com/theideasaler/calendar_date_picker2/pull/150
