### ISSUE TITLE
[Feature] How to get selection date click on ok without closing dialog.

### ISSUE THREAD

**Issue by DipakSkywave** [theideasaler/calendar_date_picker2#30]
var results = await showCalendarDatePicker2Dialog(
      context: context,
      config: CalendarDatePicker2WithActionButtonsConfig(
          calendarType: CalendarDatePicker2Type.range,
          lastDate: DateTime.now(),
          shouldCloseDialogAfterCancelTapped: true,
          okButton: InkWell(
              onTap: () {
                print('Get Selection Date=====>>>');
              },
              child: Text('OK'),
      dialogSize: Size(400, 400),
      borderRadius: BorderRadius.circular(15),
    );
    
    this is my code.
    
    Please, anyone let me know if any idea. 
    Thank you in advance.

**Comment by theideasaler** [comment]
Hi @DipakSkywave , this is not supported at the moment. If you want to implement it, I will be happy to review it. 

What needed for the PR of this feature is:

- Add a `closeDialogOnOkTapped` and add related implementation in `CalendarDatePicker2WithActionButtons`
- Set `prop ?? true` for both in `CalendarDatePicker2WithActionButtons`
- Rename `shouldCloseDialogAfterCancelTapped` to `closeDialogOnCancelTapped`

**Comment by theideasaler** [comment]
closed ticket as feature added in https://github.com/theideasaler/calendar_date_picker2/pull/33
