### ISSUE TITLE
[Feature] Calendar starts on Monday

### ISSUE THREAD

**Issue by tonbert** [theideasaler/calendar_date_picker2#31]
Thank you for your hard work, the calendar is really simple to config and works smooth.

**Is your feature request related to a problem? Please describe.**
Most european calendars starting on monday. I've seen no api for this feature so it's propably missing.

**Describe the feature you'd like**
A option to define monday as first day of week would be very nice.

![Bildschirm­foto 2022-11-08 um 15 56 29](https://user-images.githubusercontent.com/58977175/200597881-c80566de-8af3-439e-bd70-56dbf417f92c.png)

**Comment by theideasaler** [comment]
Hi @tonbert , have you tried to use localizationsDelegates? I remembered it should support different localisations.
```
localizationsDelegates: GlobalMaterialLocalizations.delegates,
      supportedLocales: const [
        Locale('en', ''),
        Locale('zh', ''),
        Locale('he', ''),
        Locale('es', ''),
        Locale('ru', ''),
      ],
```

**Comment by theideasaler** [comment]
After https://github.com/theideasaler/calendar_date_picker2/pull/33, this feature is now available inside the widget, please refer to firstDayOfWeek.

**Comment by tonbert** [comment]
This works perfect, thank you very much!
