### ISSUE TITLE
[Feature] Limit Date Range in days

### ISSUE THREAD

**Issue by tonbert** [theideasaler/calendar_date_picker2#32]
**Is your feature request related to a problem? Please describe.**
At the moment the selectable date range is unlimited. 

**Describe the feature you'd like**
An API with limitRangeInDays or similar would be nice to limit the user in max selectable days. When user is clicking a Start-Date, the days outside the limit would get slighty more gray or a custom color and they cant be selected.

**Use cases**
We have an statistics service which provides only data für 31 days. More days will result in heavy server load. This feature could give the user a direct feedback instead of an error message.

**Comment by theideasaler** [comment]
Hi @tonbert , have you tried selectableDayPredicate to limit the selectable days? You can refer to the example as a reference.

**Comment by tonbert** [comment]
This works really good when using Jiffy-Date-Manipulation. 
Thank you for your fast Feedback!

```dart
final config = CalendarDatePicker2Config(
    ...
    disabledDayTextStyle: TextStyle(
        color: Colors.grey,
    ),
);
```

```dart
CalendarDatePicker2(
...
config: config,          
selectableDayPredicate: (DateTime day) {
    if (fromDate != null && toDate == null) {
        return Jiffy(day).isBetween(fromDate, Jiffy(fromDate).add(days: 31));
    }
    return true;
},
```
