### ISSUE TITLE
Does this plugin support japanese locale ?

### ISSUE THREAD

**Issue by iamtechmanish** [theideasaler/calendar_date_picker2#51]
Does this plugin support japanese locale ?

**Comment by theideasaler** [comment]
Hi @iamtechmanish  👋
Thanks for opening an issue!

Yes, you can refer to the [example app](https://github.com/theideasaler/calendar_date_picker2/tree/main/example) and add your own locale into the `supportedLocales` list;
```
      supportedLocales: const [
        Locale('en', ''),
        Locale('zh', ''),
        Locale('he', ''),
        Locale('es', ''),
        Locale('ru', ''),
      ],
```
