### ISSUE TITLE
[Feature] Add months preview like as year preview?

### ISSUE THREAD

**Issue by logeshwaran0608** [theideasaler/calendar_date_picker2#54]
Is possible to add months preview like as year preview?...
![month_reference](https://user-images.githubusercontent.com/121167306/211280829-35d6f752-804d-4b05-b09f-564fe5305642.jpeg)

**Comment by theideasaler** [comment]
Hi @logeshwaran0608 , this is not supported in this package. 

As this feature will requires quite solid efforts of work to be implemented, so there is no plan to implement it. If you need it, you will need to implement it yourself by customising the `CalendarDatePicker2` widget.

**Comment by Maxbee** [comment]
Hello author, I hope you can support customizing the position of the year and month display centered, please consider it back?

**Comment by theideasaler** [comment]
Feature added in https://github.com/theideasaler/calendar_date_picker2/pull/167
