### ISSUE TITLE
[Feature] Can I change the ripple color when tap a day?

### ISSUE THREAD

**Issue by Mabel-BracketsLab** [theideasaler/calendar_date_picker2#59]
As the title says, can I change the color of the ripple effect when a day is selected and if so how?

I tried to change the ripple color in the ThemeData but it doesn't work.

Thanks.

**Comment by theideasaler** [comment]
Hi @Mabel-BracketsLab , this is not supported at the moment with plug-in. If you want it urgently, you will need to fork this repo and customize it as your need.
