### ISSUE TITLE
[Feature] Can I custom control value

### ISSUE THREAD

**Issue by startmt** [theideasaler/calendar_date_picker2#60]
Hi I saw this widget only have the onChange callback to send selected value but in my case I need to implement date range by auto select end date so I think I have issue with this case.

**Comment by theideasaler** [comment]
Hi @startmt , I think you case can be achieved with `CalendarDatePicker2` widget.

>_I need to implement date range by auto select end date_

All you need is to set the end date manually when you receive the start date, check out this code below:

```
CalendarDatePicker2(
          config: CalendarDatePicker2Config(calendarType: CalendarDatePicker2Type.range),
          initialValue: _rangeValueVariable,
          onValueChanged: (dates) =>
              setState(() =>
              _rangeValueVariable = [
                dates[0],
                dates[0]?.add(Duration(days: 7))
              ]),
        ),
```
