### ISSUE TITLE
[Feature] can it support korean?

### ISSUE THREAD

**Issue by jaeminlee-dev** [theideasaler/calendar_date_picker2#61]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

**Use cases**
Add use cases for the feature you're requested

**Comment by theideasaler** [comment]
Hi @jaeminlee-dev ,

yes it does support Korean.

please check out the [example app](https://github.com/theideasaler/calendar_date_picker2/blob/main/example/lib/main.dart) and you can add Locale('ko', '') into the supportedLocales array.

**Comment by jaeminlee-dev** [comment]
thanks man :)
