### ISSUE TITLE
[Feature] Clear/reset selection

### ISSUE THREAD

**Issue by joymyr** [theideasaler/calendar_date_picker2#62]
I couldn't find a way to clear the date selection. 
I use range mode, and I use the first date in the selectableDayPredicate.
In the initial state I enable all the days that aren't booked, but when one date is selected I disable all dates that comes after a booked date. The issue is that there's no way to get back to the initial state.

It would be nice if selecting the selected date again would deselect it. Alternatively I could add a reset button underneath the calendar, but then I need a way to modify the selection.

**Comment by theideasaler** [comment]
Hi @joymyr ,

The reset functionality is built-in with CalendarDatePicker2WithActionButtions widget, when you tap ‘Cancel’ the dates will be reset to initial state.
