### ISSUE TITLE
[Feature] Can i change pedding in _buildOkButton and _buildCancelButton

### ISSUE THREAD

**Issue by TheLastSupper** [theideasaler/calendar_date_picker2#63]
Can i change it

padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 15),

in **_buildOkButton** and **_buildCancelButton**

**Comment by theideasaler** [comment]
Hi @TheLastSupper ,

You can use `gapBetweenCalendarAndButtons` in the config to change the padding between buttons

**Comment by TheLastSupper** [comment]
I need remove pending.

**Comment by theideasaler** [comment]
@TheLastSupper for this default padding there is no way to change it directly. If you have to have it, then you will need to pull the code ‘CalendarDatePicker2WithActionButtons’ and customize it yourself

**Comment by theideasaler** [comment]
@TheLastSupper I can confirm this is a valid request. 

The following changes will need to be implemented:
- adding a `buttonPadding` into the `CalendarDatePicker2WithActionButtonsConfig`
- replace `const EdgeInsets.symmetric(vertical: 10, horizontal: 15)` with `buttonPadding` in `CalendarDatePicker2WithActionButtons` widget
- make sure `buttonPadding` fallbacks to `const EdgeInsets.symmetric(vertical: 10, horizontal: 15)` when it is null

You can create a PR for it if you need it urgently, otherwise I can take it some day this week.

**Comment by TheLastSupper** [comment]
@theideasaler 

I tried adding a padding button but it doesn't work.
I can wait for more solutions. Thank you.

<a href="https://freeimage.host/th"><img src="https://iili.io/HEmiGZF.png" alt="HEmiGZF.png" border="0" /></a>

**Comment by theideasaler** [comment]
@TheLastSupper buttonPadding property has been added in this PR https://github.com/theideasaler/calendar_date_picker2/pull/65

**Comment by byshy** [comment]
The space is still there even after using the `buttonPadding` and the `gapBetweenCalendarAndButtons`

```dart
final results = await showCalendarDatePicker2Dialog(
  context: context,
  config: CalendarDatePicker2WithActionButtonsConfig(
    calendarType: CalendarDatePicker2Type.range,
    selectedDayHighlightColor: Theme.of(context).primaryColor,
    centerAlignModePicker: true,
    firstDate: DateTime.now(),
    lastDate: DateTime.now().add(Duration(days: 180)),
    currentDate: DateTime.now(),
    dayTextStyle: TextStyle(fontSize: 16),
    weekdayLabelTextStyle: TextStyle(fontSize: 16),
    monthTextStyle: TextStyle(fontSize: 16),
    controlsTextStyle: TextStyle(fontSize: 16),
    buttonPadding: EdgeInsets.symmetric(horizontal: 15),
    gapBetweenCalendarAndButtons: 0,
  ),
  dialogSize: Size(
    MediaQuery.of(context).size.width * 0.9,
    MediaQuery.of(context).size.height * 0.1,
  ),
  value: [
    if (selectedStartDate != null) selectedStartDate!,
    if (selectedEndDate != null) selectedEndDate!,
  ],
);
```

<img width="306" alt="Image" src="https://github.com/user-attachments/assets/5f8c65cd-65aa-448d-8ae7-52aa30d10844" />
