### ISSUE TITLE
[Feature] I need a new feature to [select today] and [clear select].

### ISSUE THREAD

**Issue by TheLastSupper** [theideasaler/calendar_date_picker2#66]
Hello, I request feature.
Thanks for considering my request.

1.) Button (Today) => Automatic date picker today.
2.) Button (Clear) => Clear selection

<a href="https://freeimage.host/th"><img src="https://iili.io/HGdIraS.png" alt="HGdIraS.png" border="0" /></a>

**Comment by theideasaler** [comment]
Hi @TheLastSupper ,

This package is a date picker for general usage purpose. Feature request highly related to user’s own business requirements won’t be considered and should be implemented by the user self.

You might need to fork the repo and customize it to meet your needs.

**Comment by theideasaler** [comment]
Closed as the request is out of scope
