### ISSUE TITLE
[Feature]support customizing the position of the year and month display centered

### ISSUE THREAD

**Issue by Maxbee** [theideasaler/calendar_date_picker2#67]
Hello author, I hope you can support customizing the position of the year and month display centered, please consider it back?

**Comment by theideasaler** [comment]
Hi @Maxbee ,

Are you referring to centralize the year & month text and make the arrow button left and right aligned?

**Comment by theideasaler** [comment]
feature added in https://github.com/theideasaler/calendar_date_picker2/pull/69

**Comment by Maxbee** [comment]
> feature added in #69

thank you so much！
