### ISSUE TITLE
[Bug] package ignores app locale, and only shows the english one.

### ISSUE THREAD

**Issue by appregion** [theideasaler/calendar_date_picker2#8]
**Describe the bug**
It seems that the package ignore the apps locale when displaying the datepicker and shows it in english.

**To Reproduce**
1. Set other than english locale for the app.
2. Implement  CalendarDatePicker2Dialog

```
var results = await showCalendarDatePicker2Dialog(
                              context: context,
                              config: CalendarDatePicker2WithActionButtonsConfig(
                                calendarType: CalendarDatePicker2Type.range,
                                selectedDayHighlightColor:
                                    Color(AppColors.yellow),
                                okButton: Text('Выбрать'),
                                cancelButton: Text('Отмена'),
                              ),
                              dialogSize: Size(
                                  MediaQuery.of(context).size.width * 0.9, 400),
                              initialValue: [],
                              borderRadius: 10,
                            );
```
3. Call the function and open date picker

**Expected behavior**
Open the date picker and see that the days, months and weeks format is shown in the language of the apps locale.

**Actual Behaviour**
The datepicker shows everything in english.

I can see inside the CalendarDatePicker2 widget that you use MaterialLocalizations _localizations, however, it ignores the app's locale. 

I even called `print(MaterialLocalizations.of(context).narrowWeekdays);` in the same widget I call the date picker and the print result is as expected - it shows the days in the language of the app, but the date picker is still in english.

**Screenshots**
![simulator_screenshot_C005E4D6-51F3-44F2-A3AF-A3BEE2723DDC](https://user-images.githubusercontent.com/58521393/178838392-54254ee8-db40-4362-9822-1391c88b6976.png)

**Platforms (please complete the following information):**
 - Platforms: both IOS and Android

**Comment by theideasaler** [comment]
Hi @appregion , not too sure how you setup the [localisations](https://docs.flutter.dev/development/accessibility-and-localization/internationalization), but it seems working for me. I have also updated the example.
![image](https://user-images.githubusercontent.com/17869748/178860490-4a8b24b9-b345-440c-b202-6ba7778a7693.png)

**Comment by appregion** [comment]
> Hi @appregion , not too sure how you setup the [localisations](https://docs.flutter.dev/development/accessibility-and-localization/internationalization), but it seems working for me. I have also updated the [example](https://github.com/theideasaler/calendar_date_picker2/blob/main/example/lib/main.dart). ![image](https://user-images.githubusercontent.com/17869748/178860490-4a8b24b9-b345-440c-b202-6ba7778a7693.png)

My bad :( I had two material apps nested and this caused the issue :( Thanks for your swift reply and helping me solve this!
