### ISSUE TITLE
[Bug] When FirstDate is given, it is marked as disabled on the calendar

### ISSUE THREAD

**Issue by Pablo-Aldana** [theideasaler/calendar_date_picker2#80]
**Describe the bug**
If in config you select firstDate it setup the Calendar to that specific date but it won't allow you to select it again as it marks it as disable.
i.e firstDate: DateTime.now() // -> 7/03/2023
The calendar will setup this date but it won't allow you to select it anymore
**To Reproduce**
1. Create a new Calendar and in the config setup a firstDate.
2. open the Calendar
3. You'll see the firstDate on grey and it won't allow you to click it again so if for example you click on the 8th by error it won't allow you to comeback to the 7th.

`CalendarDatePicker2(
      initialValue: [],
      onValueChanged: (value) => dateChanged(value),
      config: CalendarDatePicker2WithActionButtonsConfig(
          firstDate: DateTime.now(), calendarType: CalendarDatePicker2Type.single)`

**Expected behavior**
The firstDate should be enable and ready to be selected by the user
**Actual Behaviour**
the firstDate is disabled and it does not allow the user to select it.
**Screenshots**
<img width="290" alt="image" src="https://user-images.githubusercontent.com/9969839/223536690-f41364ff-e1c5-4242-8f99-e28d5069b153.png">

**Platforms (please complete the following information):**
 - Platforms: tested just on iOS simulator haven't tried on other platforms yet

**Minimum Reproduceable Example**
`CalendarDatePicker2(
      initialValue: [],
      onValueChanged: (value) => {},
      config: CalendarDatePicker2WithActionButtonsConfig(
          firstDate: minDate, calendarType: CalendarDatePicker2Type.single)`

**Comment by theideasaler** [comment]
This bug is fixed in https://github.com/theideasaler/calendar_date_picker2/pull/81, it will be released soon

**Comment by theideasaler** [comment]
@Pablo-Aldana  please checkout new release [v0.4.2](https://pub.dev/packages/calendar_date_picker2)
