### ISSUE TITLE
[Feature] show week number

### ISSUE THREAD

**Issue by Johannes5000** [theideasaler/calendar_date_picker2#92]
Greetings,
is it possible to display the current week number next to the row?

**Comment by theideasaler** [comment]
Hi this is not supported. You will probably need to fork the code and customise it yourself.

**Comment by alejandrobalderas** [comment]
I was just thinking the same thing. This would be a great feature to have. I think the issue with using the dayBuilder is that you would override a date instead of say adding a new column that displays the week number right? @theideasaler 


Cheers

**Comment by theideasaler** [comment]
@alejandrobalderas That's true. In this case probably another solution is to wrap `CalendarDatePicker2` inside a custom widget and place a separate `Column` beside it, update the week number in the column by listening to `onDisplayedMonthChanged`

Last solution will be fork this repo and add the custom logics into `calendar_date_picker2.dart`.

**Comment by tomasbaran** [comment]
I need this too
